### ISSUE TITLE
SQLite extension needed for UWP

### ISSUE THREAD

**Issue by mattleibow** [xamarin/dev-days-labs#14]
We should probably mention this in the handson readme:

http://sqlite.org/download.html
http://sqlite.org/2016/sqlite-uwp-3140200.vsix

**Comment by jamesmontemagno** [comment]
Yup, it is in the readme to add it via the Extensions and Updates.

**Comment by jamesmontemagno** [comment]
Before this weekend, I will be updating to 3.0, which should solve this issue in the future ;)

**Comment by toolboc** [comment]
I am still seeing this issue in latest code.  I also did not see a mention of installing vis Extension and Updates in the latest Readme.

**Comment by jamesmontemagno** [comment]
It can simply be removed. I am pretty sure I removed it... hmmmm

**Comment by jamesmontemagno** [comment]
Now removed removed :) thanks!
